"""One-shot guarded migration of release/CI tooling to the Windows-only support model."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write_lf(path: str, text: str) -> None:
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    (ROOT / path).write_bytes(normalized.encode("utf-8"))


def replace_exact(path: str, old: str, new: str) -> None:
    text = read(path)
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{path}: expected one exact anchor, found {count}")
    write_lf(path, text.replace(old, new, 1))


def replace_regex(path: str, pattern: str, replacement: str) -> None:
    text = read(path)
    regex = re.compile(pattern, re.MULTILINE | re.DOTALL)
    matches = list(regex.finditer(text))
    if len(matches) != 1:
        raise RuntimeError(f"{path}: expected one regex anchor, found {len(matches)}")
    write_lf(path, regex.sub(lambda _m: replacement, text, count=1))


# Explicit checkout policy: Windows scripts use CRLF; language/tooling sources use LF.
write_lf(
    ".gitattributes",
    """*.go text eol=lf
*.py text eol=lf
*.yml text eol=lf
*.yaml text eol=lf
*.ps1 text eol=crlf
*.bat text eol=crlf
""",
)

# POSIX release tooling is intentionally removed. The application and its release
# contract are Windows-only; the canonical engine is scripts/windows/IrisTools.ps1.
for relative in (
    "scripts/release-gate.sh",
    "scripts/build-release.sh",
    "scripts/release-tools.sh",
):
    path = ROOT / relative
    if not path.is_file():
        raise RuntimeError(f"required legacy release file is missing: {relative}")
    path.unlink()

# Make Python test imports and bytecode placement deterministic on Windows.
windows_tooling = "scripts/windows/IrisTools.ps1"
replace_regex(
    windows_tooling,
    r"^function Test-Release \{.*?(?=^function Clear-BuildGenerated \{)",
    r'''function Clear-PythonGenerated {
    foreach ($RelativePath in @("tools\__pycache__", "tests\__pycache__")) {
        $Target = Join-Path $Root $RelativePath
        if (Test-Path -LiteralPath $Target -PathType Container) {
            Remove-Item -LiteralPath $Target -Recurse -Force
        }
    }
}

function Test-Release {
    Assert-CleanTree
    Test-WindowsTooling
    Ensure-AuditEnvironment

    $SavedPythonPath = [Environment]::GetEnvironmentVariable("PYTHONPATH", "Process")
    $SavedPyCachePrefix = [Environment]::GetEnvironmentVariable("PYTHONPYCACHEPREFIX", "Process")
    $ToolsPath = Join-Path $Root "tools"
    $ExternalPyCache = Join-Path $ToolRoot "release-test-pycache"
    Remove-Item -LiteralPath $ExternalPyCache -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path $ExternalPyCache | Out-Null
    if ($SavedPythonPath) {
        $env:PYTHONPATH = $ToolsPath + [IO.Path]::PathSeparator + $SavedPythonPath
    } else {
        $env:PYTHONPATH = $ToolsPath
    }
    $env:PYTHONPYCACHEPREFIX = $ExternalPyCache

    # Remove only known generated bytecode left by an interrupted/older Windows
    # gate. Any cache recreated by this run remains visible to the final audit.
    Clear-PythonGenerated

    Push-Location $Root
    try {
        if ((& go env GOVERSION).Trim() -ne "go$GoPin") { throw "Go version mismatch." }
        $WailsExecutable = Get-PinnedWailsExecutable
        Write-Host "Wails: $WailsPin @ $WailsExecutable"
        $BeforeHead = (& git rev-parse HEAD).Trim()
        Invoke-Checked $AuditPython @("-B", "tools/repository_audit.py") 120
        $GoFiles = Get-ChildItem -LiteralPath $Root -Filter "*.go" -File | ForEach-Object { $_.FullName }
        $Unformatted = (& gofmt -l -- $GoFiles)
        if ($LASTEXITCODE -ne 0) { throw "gofmt failed." }
        if ($Unformatted) { throw "Go source is not formatted." }
        Invoke-Checked "go" @("mod", "verify") 180
        Invoke-Checked "go" @("mod", "tidy", "-diff") 180
        Invoke-Checked "go" @("build", "-trimpath", "-o", (Join-Path $env:TEMP "iris-build-probe.exe"), ".") 600
        Invoke-Checked "go" @("test", "-count=1", "./...") 900
        Invoke-Checked "go" @("vet", "./...") 600
        Invoke-Staticcheck @("./...")
        Invoke-Govulncheck
        Invoke-Checked $AuditPython @("-m", "compileall", "-q", "tools", "tests") 120
        $LegacyTests = @(Get-ChildItem -LiteralPath (Join-Path $Root "tools") -Filter "test_*.py" -File -ErrorAction SilentlyContinue)
        if ($LegacyTests.Count -ne 0) { throw "Python regression tests must live in tests/, not tools/." }
        Invoke-Checked $AuditPython @("-B", "-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py") 600
        Invoke-Checked (Join-Path $AuditEnv "Scripts\ruff.exe") @("check", "--no-cache", ".") 300
        Invoke-Checked (Join-Path $AuditEnv "Scripts\ruff.exe") @("format", "--check", "--no-cache", ".") 300
        Invoke-Checked (Join-Path $AuditEnv "Scripts\bandit.exe") @("-q", "-r", "tools") 300
        Invoke-Checked (Join-Path $AuditEnv "Scripts\pip-audit.exe") @("--local", "--cache-dir", (Join-Path $AuditEnv "pip-audit-cache")) 600
        Invoke-Checked $AuditPython @("-B", "tools/validate_workflows.py") 120
        Invoke-Checked "node" @("--check", "web/app.js") 120
        foreach ($Audit in @("data_presentation_audit.py", "frontend_smoke_test.py")) {
            Invoke-Checked $AuditPython @("-B", ("tools/" + $Audit)) 900
        }
        $GitleaksExecutable = Join-Path $PinnedGitleaksDirectory "gitleaks.exe"
        Test-GitleaksDetection
        Invoke-Checked $GitleaksExecutable @("dir", "--no-banner", "--redact", ".") 600
        Invoke-GitleaksHistoryScan 600
        Invoke-Checked $AuditPython @("-B", "tools/repository_audit.py") 120
        Assert-CleanTree
        if ((& git rev-parse HEAD).Trim() -ne $BeforeHead) { throw "HEAD changed during the RELEASE gate." }
        Invoke-Checked $AuditPython @("-B", "tools/release_fingerprint.py", "--write") 120
        Write-Host "RELEASE gate: PASS" -ForegroundColor Green
    } finally {
        Pop-Location
        [Environment]::SetEnvironmentVariable("PYTHONPATH", $SavedPythonPath, "Process")
        [Environment]::SetEnvironmentVariable("PYTHONPYCACHEPREFIX", $SavedPyCachePrefix, "Process")
        Remove-Item -LiteralPath $ExternalPyCache -Recurse -Force -ErrorAction SilentlyContinue
    }
}

''',
)
replace_exact(
    windows_tooling,
    '$RequiredChecks = @("Linux quality and security", "Go race detector", "Native Windows Wails release matrix", "Analyze (go)", "Analyze (python)")',
    '$RequiredChecks = @("Windows quality and security", "Windows race detector", "Native Windows Wails release matrix", "Analyze (go)", "Analyze (python)")',
)
replace_exact(
    windows_tooling,
    "        # A source archive can be created on Unix with core.filemode=true. After the\n        # archive is extracted on NTFS, Git for Windows cannot preserve Unix execute\n        # bits and otherwise reports executable shell scripts as modified even when\n        # their contents are byte-for-byte identical to the index.\n",
    "        # NTFS does not preserve POSIX executable-bit semantics. Disable file-mode\n        # tracking before the cleanliness check so Windows metadata cannot create a\n        # false modified state for byte-identical tracked files.\n",
)
replace_exact(
    windows_tooling,
    'Write-Host "Commit published. GitHub CI and CodeQL must be PASS before GITHUB RELEASE." -ForegroundColor Green',
    'Write-Host "Commit published. Windows CI and CodeQL must be PASS before GITHUB RELEASE." -ForegroundColor Green',
)

# Canonical Windows-only CI. The quality job prepares only external/pinned tools,
# then executes the same local IrisTools.ps1 Test gate on a local main ref.
write_lf(
    ".github/workflows/ci.yml",
    r'''name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GOTOOLCHAIN: local
  GITLEAKS_VERSION: 8.30.1
  GITLEAKS_WINDOWS_X64_SHA256: d29144deff3a68aa93ced33dddf84b7fdc26070add4aa0f4513094c8332afc4e

jobs:
  windows-quality:
    name: Windows quality and security
    runs-on: windows-2025
    timeout-minutes: 55
    steps:
      - name: Checkout canonical source and history
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Python 3.13
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: tools/requirements-audit.txt

      - name: Setup pinned Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .go-version
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - name: Prepare pinned Windows quality tools
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)

          $env:GOBIN = Join-Path $env:RUNNER_TEMP "go-tools"
          New-Item -ItemType Directory -Force -Path $env:GOBIN | Out-Null
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.14.0
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          go install honnef.co/go/tools/cmd/staticcheck@2026.1
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          [IO.File]::AppendAllText($env:GITHUB_ENV, "GOBIN=$env:GOBIN" + [Environment]::NewLine, $utf8NoBom)
          [IO.File]::AppendAllText($env:GITHUB_PATH, $env:GOBIN + [Environment]::NewLine, $utf8NoBom)

          $toolRoot = Join-Path $env:LOCALAPPDATA "IrisOnlineDatabase\BuildTools"
          New-Item -ItemType Directory -Force -Path $toolRoot | Out-Null
          $auditEnv = Join-Path $toolRoot "python-audit"
          Remove-Item -LiteralPath $auditEnv -Recurse -Force -ErrorAction SilentlyContinue
          python -m venv $auditEnv
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          $auditPython = Join-Path $auditEnv "Scripts\python.exe"
          & $auditPython -m pip install --disable-pip-version-check --requirement tools\requirements-audit.txt
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          & $auditPython -B tools\verify_python_environment.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          & $auditPython -m pip check
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          Set-Content -LiteralPath (Join-Path $toolRoot "python-audit-active.txt") -Value $auditEnv -Encoding UTF8
          [IO.File]::AppendAllText($env:GITHUB_PATH, (Join-Path $auditEnv "Scripts") + [Environment]::NewLine, $utf8NoBom)

          $playwrightPath = Join-Path $toolRoot "playwright"
          New-Item -ItemType Directory -Force -Path $playwrightPath | Out-Null
          $env:PLAYWRIGHT_BROWSERS_PATH = $playwrightPath
          & $auditPython -m playwright install chromium
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          [IO.File]::AppendAllText($env:GITHUB_ENV, "PLAYWRIGHT_BROWSERS_PATH=$playwrightPath" + [Environment]::NewLine, $utf8NoBom)

          $archiveName = "gitleaks_$env:GITLEAKS_VERSION`_windows_x64.zip"
          $checksumsName = "gitleaks_$env:GITLEAKS_VERSION`_checksums.txt"
          $base = "https://github.com/gitleaks/gitleaks/releases/download/v$env:GITLEAKS_VERSION"
          $archive = Join-Path $env:RUNNER_TEMP $archiveName
          $checksums = Join-Path $env:RUNNER_TEMP $checksumsName
          Invoke-WebRequest -UseBasicParsing -Uri "$base/$archiveName" -OutFile $archive
          Invoke-WebRequest -UseBasicParsing -Uri "$base/$checksumsName" -OutFile $checksums
          $expectedLine = Get-Content -LiteralPath $checksums | Where-Object { $_ -match [Regex]::Escape($archiveName) } | Select-Object -First 1
          if (-not $expectedLine) { throw "Official Gitleaks checksum is missing." }
          $expected = ($expectedLine -split "\s+")[0].ToLowerInvariant()
          $actual = (Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash.ToLowerInvariant()
          if ($expected -ne $env:GITLEAKS_WINDOWS_X64_SHA256 -or $actual -ne $expected) {
            throw "Pinned Gitleaks checksum verification failed."
          }
          $gitleaksDir = Join-Path $toolRoot "gitleaks-$env:GITLEAKS_VERSION"
          Remove-Item -LiteralPath $gitleaksDir -Recurse -Force -ErrorAction SilentlyContinue
          Expand-Archive -LiteralPath $archive -DestinationPath $gitleaksDir -Force
          $gitleaks = Join-Path $gitleaksDir "gitleaks.exe"
          if ((& $gitleaks version | Out-String).Trim() -ne $env:GITLEAKS_VERSION) {
            throw "Pinned Gitleaks executable version mismatch."
          }

      - name: Run canonical Windows release gate
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          git config --local core.filemode false
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          # GitHub pull-request checkouts may be detached. The local ref name is
          # normalized only inside this disposable runner; the commit is unchanged.
          git checkout -B main HEAD
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action Test
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

  windows-race:
    name: Windows race detector
    runs-on: windows-2025
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup pinned Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .go-version
          cache: true
      - name: Windows amd64 race detector
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $gcc = Get-Command gcc.exe -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
          if (-not $gcc) { throw "Windows race detector requires gcc.exe on the GitHub runner." }
          & $gcc.Source --version
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          $syncArchive = (& $gcc.Source -print-file-name=libsynchronization.a | Out-String).Trim()
          if (-not $syncArchive -or $syncArchive -eq "libsynchronization.a" -or -not (Test-Path -LiteralPath $syncArchive -PathType Leaf)) {
            throw "Windows MinGW runtime is too old for the Go race detector."
          }
          $env:CGO_ENABLED = "1"
          go test -race -count=1 ./...
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

  windows-build:
    name: Native Windows Wails release matrix
    runs-on: windows-2025
    needs: [windows-quality, windows-race]
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python 3.13
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.13'

      - name: Setup pinned Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .go-version
          cache: true

      - name: Install pinned Windows release Go tools
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          if (-not $env:RUNNER_TEMP) { throw "RUNNER_TEMP is unavailable." }
          $env:GOBIN = Join-Path $env:RUNNER_TEMP "go-tools"
          New-Item -ItemType Directory -Force -Path $env:GOBIN | Out-Null
          go install github.com/wailsapp/wails/v2/cmd/wails@v2.14.0
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          go install honnef.co/go/tools/cmd/staticcheck@2026.1
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          [IO.File]::AppendAllText($env:GITHUB_ENV, "GOBIN=$env:GOBIN" + [Environment]::NewLine, $utf8NoBom)
          [IO.File]::AppendAllText($env:GITHUB_PATH, $env:GOBIN + [Environment]::NewLine, $utf8NoBom)

      - name: Parse and self-test Windows PowerShell 5.1 tooling
        shell: powershell
        run: |
          $files = @("IrisTools.ps1", "scripts\windows\IrisTools.ps1")
          foreach ($file in $files) {
            $tokens = $null
            $errors = $null
            [System.Management.Automation.Language.Parser]::ParseFile(
              (Resolve-Path -LiteralPath $file).Path,
              [ref]$tokens,
              [ref]$errors
            ) | Out-Null
            if ($errors.Count -ne 0) {
              Write-Host "PowerShell syntax: FAIL [PS_PARSE] file=$file count=$($errors.Count)"
              exit 1
            }
          }
          powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action SelfTest
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Windows Go tests
        shell: powershell
        run: |
          $driveRoot = [IO.Path]::GetPathRoot($env:GITHUB_WORKSPACE)
          $testTemp = Join-Path $driveRoot ("iris-go-test-temp-$env:GITHUB_RUN_ID-$env:GITHUB_RUN_ATTEMPT")
          New-Item -ItemType Directory -Force -Path $testTemp | Out-Null
          $oldTemp = $env:TEMP
          $oldTmp = $env:TMP
          $oldTmpDir = $env:TMPDIR
          $goTestExitCode = 0
          try {
            $env:TEMP = $testTemp
            $env:TMP = $testTemp
            $env:TMPDIR = $testTemp
            go test -count=1 ./...
            $goTestExitCode = $LASTEXITCODE
          } finally {
            $env:TEMP = $oldTemp
            $env:TMP = $oldTmp
            $env:TMPDIR = $oldTmpDir
            Remove-Item -LiteralPath $testTemp -Recurse -Force -ErrorAction SilentlyContinue
          }
          if ($goTestExitCode -ne 0) { exit $goTestExitCode }

      - name: Build production desktop executables and SHA256 (x64, x86, arm64)
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          $version = (Get-Content VERSION -Raw).Trim()
          $head = (git rev-parse HEAD).Trim()
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          $artifactDir = Join-Path $env:RUNNER_TEMP "iris-release-multiarch"
          Remove-Item -LiteralPath $artifactDir -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Force -Path $artifactDir | Out-Null
          $wails = Join-Path $env:GOBIN "wails.exe"
          if (-not (Test-Path -LiteralPath $wails -PathType Leaf)) { throw "Pinned Wails executable is missing." }
          $targets = @(
            [pscustomobject]@{ Platform = "windows/amd64"; Suffix = "x64"; LevelName = "GOAMD64"; LevelValue = "v1" },
            [pscustomobject]@{ Platform = "windows/386"; Suffix = "x86"; LevelName = "GO386"; LevelValue = "sse2" },
            [pscustomobject]@{ Platform = "windows/arm64"; Suffix = "arm64"; LevelName = "GOARM64"; LevelValue = "v8.0" }
          )
          $environmentNames = @("CGO_ENABLED", "GOAMD64", "GO386", "GOARM64")
          $savedEnvironment = @{}
          foreach ($name in $environmentNames) {
            $savedEnvironment[$name] = [Environment]::GetEnvironmentVariable($name, "Process")
          }
          $artifacts = New-Object System.Collections.Generic.List[string]
          try {
            foreach ($target in $targets) {
              Remove-Item Env:\GOAMD64 -ErrorAction SilentlyContinue
              Remove-Item Env:\GO386 -ErrorAction SilentlyContinue
              Remove-Item Env:\GOARM64 -ErrorAction SilentlyContinue
              $env:CGO_ENABLED = "0"
              Set-Item -Path "Env:$($target.LevelName)" -Value $target.LevelValue
              & $wails build -platform $target.Platform -webview2 embed -trimpath -clean -skipbindings -s -nosyncgomod -m -o IrisOnlineDatabase.exe -ldflags "-buildid= -X main.appVersion=$version -X main.releaseMarker=IrisOnlineRelease/$version/$head"
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
              $artifact = Join-Path $artifactDir "IrisOnlineDB-$version-Windows-$($target.Suffix).exe"
              Copy-Item build\bin\IrisOnlineDatabase.exe $artifact -Force
              $artifacts.Add($artifact)
            }
          } finally {
            foreach ($name in $environmentNames) {
              $value = $savedEnvironment[$name]
              if ($null -eq $value) {
                Remove-Item -Path "Env:$name" -ErrorAction SilentlyContinue
              } else {
                Set-Item -Path "Env:$name" -Value $value
              }
            }
            Remove-Item build\bin, build\generated, web\wailsjs -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item build\appicon.png -Force -ErrorAction SilentlyContinue
          }
          $checksumLines = foreach ($artifact in $artifacts) {
            $hash = (Get-FileHash -LiteralPath $artifact -Algorithm SHA256).Hash.ToLowerInvariant()
            "$hash  $(Split-Path $artifact -Leaf)"
          }
          Set-Content -LiteralPath (Join-Path $artifactDir "SHA256SUMS.txt") -Value $checksumLines -Encoding ASCII
          python -B tools/verify_release_assets.py --directory $artifactDir --version $version
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          python -B tools/verify_executables.py --directory $artifactDir --version $version
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          python -B tools/verify_windows_resources.py --directory $artifactDir --version $version
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Source tree remains clean
        shell: powershell
        run: |
          python -B tools/repository_audit.py
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          git diff --exit-code
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          $status = @(git status --porcelain=v1 --untracked-files=all)
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          if ($status.Count -ne 0) {
            $status | ForEach-Object { Write-Host $_ }
            exit 1
          }
''',
)

write_lf(
    ".github/workflows/codeql.yml",
    r'''name: CodeQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '31 3 * * 2'

permissions:
  contents: read
  security-events: write

env:
  GOTOOLCHAIN: local

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: windows-2025
    timeout-minutes: 35
    strategy:
      fail-fast: false
      matrix:
        language: [go, python]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup pinned Go
        if: matrix.language == 'go'
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: .go-version
          cache: true
      - name: Initialize CodeQL
        uses: github/codeql-action/init@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
        with:
          languages: ${{ matrix.language }}
      - name: Build Windows Go sources
        if: matrix.language == 'go'
        shell: powershell
        run: |
          $ErrorActionPreference = "Stop"
          go test -count=1 ./...
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          go build -trimpath -o (Join-Path $env:RUNNER_TEMP "iris-codeql.exe") .
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      - name: Analyze
        uses: github/codeql-action/analyze@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
''',
)

write_lf(
    ".github/workflows/dependency-review.yml",
    r'''name: Dependency Review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Dependency review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: high
''',
)

write_lf(
    "tools/validate_workflows.py",
    r'''"""Validate GitHub workflow YAML before a release reaches GitHub."""

from __future__ import annotations

import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ACTION_PIN = re.compile(r"^\s*uses:\s*[^@\s]+@([0-9a-f]{40})(?:\s|$)", re.MULTILINE)
ACTION_REFERENCE = re.compile(r"^\s*uses:\s*[^@\s]+@([^\s#]+)", re.MULTILINE)
EXPRESSION = re.compile(r"\$\{\{(.*?)\}\}", re.DOTALL)
JOB_ENV_DISALLOWED_CONTEXT = re.compile(r"\b(?:env|job|runner|steps)\.")


def invalid_job_env_contexts(document: dict[object, object]) -> int:
    jobs = document.get("jobs")
    if not isinstance(jobs, dict):
        return 0
    failures = 0
    for job in jobs.values():
        if not isinstance(job, dict):
            continue
        job_env = job.get("env")
        if not isinstance(job_env, dict):
            continue
        for value in job_env.values():
            if not isinstance(value, str):
                continue
            for expression in EXPRESSION.findall(value):
                if JOB_ENV_DISALLOWED_CONTEXT.search(expression):
                    failures += 1
    return failures


def release_policy_failures() -> int:
    failures = 0
    ci_path = ROOT / ".github" / "workflows" / "ci.yml"
    codeql_path = ROOT / ".github" / "workflows" / "codeql.yml"
    dependency_path = ROOT / ".github" / "workflows" / "dependency-review.yml"
    try:
        ci = ci_path.read_text(encoding="utf-8")
        codeql = codeql_path.read_text(encoding="utf-8")
        dependency = dependency_path.read_text(encoding="utf-8")
    except OSError:
        return 1

    required_checks = (
        "name: Windows quality and security",
        "name: Windows race detector",
        "name: Native Windows Wails release matrix",
    )
    if any(marker not in ci for marker in required_checks):
        failures += 1
    if "ubuntu-" in ci or "ubuntu-" in codeql or "ubuntu-" in dependency:
        failures += 1
    if ci.count("runs-on: windows-2025") < 3:
        failures += 1
    if "runs-on: windows-2025" not in codeql or "runs-on: windows-2025" not in dependency:
        failures += 1
    if (
        "name: Analyze (${{ matrix.language }})" not in codeql
        or "language: [go, python]" not in codeql
        or "Build Windows Go sources" not in codeql
    ):
        failures += 1

    windows_start = ci.find("  windows-build:")
    if windows_start < 0:
        failures += 1
        return failures
    windows = ci[windows_start:]
    ordered_steps = (
        "- name: Setup Python 3.13",
        "- name: Setup pinned Go",
        "- name: Install pinned Windows release Go tools",
        "- name: Parse and self-test Windows PowerShell 5.1 tooling",
    )
    positions = [windows.find(marker) for marker in ordered_steps]
    if any(position < 0 for position in positions) or positions != sorted(positions):
        failures += 1
    for marker in (
        "wails@v2.14.0",
        "staticcheck@2026.1",
        "govulncheck@v1.6.0",
        'Platform = "windows/amd64"',
        'Platform = "windows/386"',
        'Platform = "windows/arm64"',
        "verify_release_assets.py",
        "verify_executables.py",
        "verify_windows_resources.py",
    ):
        if marker not in windows:
            failures += 1
    for marker in (
        "Run canonical Windows release gate",
        "IrisTools.ps1 -Action Test",
        "GITLEAKS_WINDOWS_X64_SHA256",
        "playwright install chromium",
        "Windows amd64 race detector",
        "go test -race -count=1 ./...",
        "libsynchronization.a",
    ):
        if marker not in ci:
            failures += 1
    return failures


def main() -> int:
    failures = 0
    workflows = sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    if not workflows:
        print("Workflow validation: FAIL [WF001] count=1")
        return 1

    for path in workflows:
        text = path.read_text(encoding="utf-8")
        try:
            document = yaml.safe_load(text)
        except yaml.YAMLError:
            failures += 1
            continue
        if not isinstance(document, dict) or not isinstance(document.get("jobs"), dict):
            failures += 1
            continue
        failures += invalid_job_env_contexts(document)
        references = ACTION_REFERENCE.findall(text)
        pins = ACTION_PIN.findall(text)
        if len(references) != len(pins):
            failures += 1

    failures += release_policy_failures()

    if failures:
        print(f"Workflow validation: FAIL [WF001] count={failures}")
        return 1
    print(f"Workflow validation: PASS files={len(workflows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
''',
)

# Documentation: one Windows release contract; no POSIX release path.
write_lf(
    "docs/BUILD.md",
    r'''# Сборка и проверки

## Поддерживаемая среда

Iris Online Database — Windows desktop-приложение. Канонические локальные проверки, сборка и выпуск выполняются только в Windows 10/11 через PowerShell 5.1+.

Закреплённые зависимости:

- публикуемые цели: Windows x64 (`amd64`), x86 (`386`) и ARM64 (`arm64`);
- Go 1.26.6 — единственный pin находится в `.go-version`;
- Wails CLI 2.14.0;
- Git, Python 3.13 и Node.js 24;
- Staticcheck 2026.1 и govulncheck 1.6.0;
- Python tools — только `tools/requirements-audit.txt`;
- Gitleaks 8.30.1 для Windows x64 с обязательной проверкой SHA-256;
- Microsoft Edge WebView2 Runtime.

`go.mod` задаёт совместимость зависимостей, а фактический воспроизводимый toolchain выбирается `.go-version`. На Windows `Install` не зависит от задержки каталога Winget для Go: exact `windows-amd64` ZIP загружается из `go.dev`, размер и SHA-256 сверяются с официальными release metadata, после чего проверяется фактический `go version`. Проверенный toolchain хранится versioned под `%LOCALAPPDATA%\IrisOnlineDatabase\BuildTools` и ставится первым в process `PATH`; системная установка Go не перезаписывается.

## Команды Windows

Откройте PowerShell в корне репозитория:

```powershell
powershell -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action Check
powershell -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action Install
powershell -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action Test
powershell -ExecutionPolicy Bypass -File .\IrisTools.ps1 -Action Build -OutputDirectory C:\IrisRelease\2.0.1
```

Для отдельного запуска строгого теста в прежнем формате используйте поставляемый отдельно `01_TEST.bat`: храните его рядом с папкой `iris-online-database`, а не внутри source. Это только launcher: он находит корневой `IrisTools.ps1`, вызывает `-Action Test`, возвращает тот же exit code и делает `pause`, но не содержит второй копии release-проверок.

Корневой launcher автоматически запрашивает повышение через Windows UAC для `Check` и `Install`. `Test`, `Build`, `Publish` и `Release` выполняются с обычными правами. `Install` повторно использует Python audit venv и Playwright cache под `%LOCALAPPDATA%\IrisOnlineDatabase\BuildTools`; source не загрязняется.

Windows gate сам задаёт `PYTHONPATH` для `tools` и выносит `PYTHONPYCACHEPREFIX` из source. Старые `tools\__pycache__` и `tests\__pycache__` удаляются перед первой проверкой как известные generated-каталоги; если текущий запуск создаст их снова, финальный repository audit завершится ошибкой. Python и Go checkout-ятся с LF согласно `.gitattributes`, поэтому глобальный `core.autocrlf` не должен создавать ложные ошибки Ruff/gofmt.

## Обязательные проверки

`IrisTools.ps1 -Action Test` выполняет fail-closed gate: repository hygiene, gofmt, module verify/tidy-diff, Windows build probe, Go tests и vet, Staticcheck, govulncheck, Python unittest, Ruff lint/format, Bandit, full installed-environment pip-audit, YAML/action-pin validation, audit встроенной проекции данных, JS syntax, deterministic Playwright smoke, Gitleaks current/history и повторную Git cleanliness проверку. Fingerprint записывается только после полного PASS.

GitHub CI использует Windows Server 2025. Отдельно выполняются тот же Windows quality/security gate, Windows `amd64` race detector и Wails-сборка x64/x86/ARM64. CodeQL и dependency review для release-контуров также выполняются на Windows runners. Linux не является поддерживаемой платформой приложения и не входит в release gate.

Release build последовательно собирает Windows x64 (`windows/amd64`, `GOAMD64=v1`), x86 (`windows/386`, `GO386=sse2`) и ARM64 (`windows/arm64`, `GOARM64=v8.0`). Для каждой цели явно устанавливается `CGO_ENABLED=0`, а исходное process environment восстанавливается после сборки. Каждый EXE проходит проверку Go/Wails metadata, PE architecture, Windows resources и hardening flags.

`raw_projection_audit.py` и `drop_table_audit.py` остаются отдельными read-only forensic-инструментами для исходных игровых таблиц, которые не распространяются с приложением. Их нельзя выдавать за CI PASS без явных входных ресурсов; production assets проверяются `data_presentation_audit.py`, exact SHA-256 и regression-тестами.

Security/network checks ограничены watchdog. `govulncheck` использует официальную Go vulnerability database, повторяет сетевую попытку и применяет канонический fallback. Если база недоступна, статус уязвимостей остаётся `UNKNOWN`, а gate завершается ошибкой без fingerprint. Сообщение `PASS` означает реальное успешное выполнение.
''',
)

write_lf(
    "docs/RELEASE.md",
    r'''# Release process

Выпуск Iris Online Database выполняется только из Windows и только из единственного канонического Git working tree. Не создавайте отдельную GitHub-копию source.

## Порядок

1. На `main` закоммитьте все изменения и убедитесь, что `git status` чист.
2. `IrisTools.ps1 -Action Test` запускает строгий Windows gate. Только после PASS в `.git/iris-release-fingerprint.json` атомарно записываются source SHA-256, HEAD, branch, version, tracked file count, UTC timestamp и toolchain.
3. `IrisTools.ps1 -Action Build -OutputDirectory <внешняя папка>` повторно проверяет fingerprint и создаёт `IrisOnlineDB-2.0.1-Windows-x64.exe`, `IrisOnlineDB-2.0.1-Windows-x86.exe`, `IrisOnlineDB-2.0.1-Windows-arm64.exe` плюс единый `SHA256SUMS.txt` вне source.
4. Повторите сборку в чистой внешней папке и сравните SHA-256. Расхождение — release blocker.
5. `IrisTools.ps1 -Action Publish` ещё раз проверяет fingerprint и отправляет ровно проверенный HEAD в `origin/main`.
6. Дождитесь PASS обязательных Windows CI, Windows race, Windows Wails matrix и CodeQL checks для этого HEAD.
7. `IrisTools.ps1 -Action Release` проверяет remote HEAD/check-runs, локальные artifacts, создаёт подписанный `v2.0.1` tag и GitHub release с ранее проверенными файлами.

Любое tracked/untracked изменение source, другой HEAD/branch или отсутствующий/устаревший fingerprint блокирует build/publish/release. Build удаляет только известные generated Wails paths и проверяет, что Git state не изменился.

Source ZIP формируется отдельно от EXE и не содержит release artifacts, caches, venv или stale fingerprint. После упаковки ZIP нужно распаковать в Windows, сравнить manifest hashes, запустить repository audit и повторить secret scan.
''',
)

write_lf(
    "CONTRIBUTING.md",
    r'''# Участие в разработке

Работайте только в одном клоне репозитория. Не копируйте source в соседний `github-repo`, `release-files` или временный publish tree.

Перед pull request:

1. Прочитайте `docs/BUILD.md` и используйте Go из `.go-version`.
2. Обновляйте код, тесты, Windows CI и документацию в одном изменении.
3. Не изменяйте игровые assets механически. Для осознанного изменения обновите соответствующий builder, audit, checksum и объяснение.
4. Не добавляйте secrets, EXE, coverage, caches, virtualenv, `.syso` или Playwright downloads в source.
5. Запустите канонический Windows gate через `IrisTools.ps1 -Action Test` перед подготовкой релиза.

Python tools запускаются как `python -B tools/name.py`, поэтому в них нет shebang и executable bit. Release tooling проекта — только Windows PowerShell/Batch; отдельного POSIX/Linux release path нет.

Новая production dependency требует обоснования, проверки лицензии и security review. Vanilla frontend не использует npm framework; Wails — desktop runtime dependency v2.

## Постоянные правила качества

- Производительность — обязательное требование. Не добавляйте лишние перерисовки, декоративные анимации, тяжёлые зависимости или фоновые операции без измеримой пользы. Интерфейс должен оставаться удобным на старых и слабых ПК.
- Не дублируйте одну и ту же информацию в разных разделах без необходимости. Используйте один источник истины и связывайте сущности переходами вместо повторения больших блоков данных.
- Перед окончательным изменением любого пользовательского текста проводите проверку: орфография → пунктуация → грамматика → фактический смысл → понятность → краткость → единообразие терминологии → соответствие элементу интерфейса. Не меняйте фактический смысл ради стиля.
- При каждом изменении интерфейса перепроверяйте видимый текст, даты и версии. `VERSION`, версия в `web/app.js`, `web/index.html` и заголовок `README.md` должны оставаться согласованными. Номер версии меняется только в рамках реального релиза.
- Минимизируйте шум в GitHub. Для ручных изменений объединяйте один логический набор в один PR и один squash-commit в `main`. Автоматика должна создавать коммит только при содержательном изменении данных, а не из-за времени проверки, косметического формата или эквивалентного текста.
''',
)

# Quality contract no longer has or tests a POSIX release gate.
replace_exact(
    "tests/test_quality_contract.py",
    '''        cls.release_gate = (ROOT / "scripts/release-gate.sh").read_text(\n            encoding="utf-8"\n        )\n''',
    "",
)
replace_regex(
    "tests/test_quality_contract.py",
    r"^    def test_release_gates_run_current_python_regression_suite\(self\):.*?(?=^    def test_item_page_does_not_duplicate_recipe_materials)",
    r'''    def test_windows_release_gate_runs_current_python_regression_suite(self):
        self.assertIn(
            '"discover", "-s", "tests", "-p", "test_*.py"',
            self.windows_release_tools,
        )
        self.assertNotIn(
            '"discover", "-s", "tools", "-p", "test_*.py"',
            self.windows_release_tools,
        )
        self.assertIn('@("-q", "-r", "tools")', self.windows_release_tools)
        self.assertIn('$env:PYTHONPATH = $ToolsPath', self.windows_release_tools)
        self.assertIn('$env:PYTHONPYCACHEPREFIX = $ExternalPyCache', self.windows_release_tools)
        self.assertIn("Clear-PythonGenerated", self.windows_release_tools)

''',
)

# Release regression tests are rewritten to validate one Windows source of truth.
release_helpers = "tests/test_release_helpers.py"
replace_regex(
    release_helpers,
    r"^    def test_release_build_is_external_and_fingerprint_gated\(self\):.*?(?=^    def test_optional_test_launcher_is_kept_outside_source)",
    r'''    def test_release_build_is_external_and_fingerprint_gated(self):
        launcher = (ROOT / "IrisTools.ps1").read_text(encoding="utf-8")
        windows = (ROOT / "scripts" / "windows" / "IrisTools.ps1").read_text(
            encoding="utf-8"
        )
        self.assertEqual(
            [(target.goarch, target.asset_suffix) for target in RELEASE_TARGETS],
            [("amd64", "x64"), ("386", "x86"), ("arm64", "arm64")],
        )
        self.assertIn("scripts\\windows\\IrisTools.ps1", launcher)
        for marker in (
            "release_fingerprint.py",
            "windows/amd64",
            "windows/386",
            "windows/arm64",
            "IrisOnlineDB-$Version-Windows-$($Target.Suffix).exe",
            "webview2",
            "IrisOnlineDatabase.exe",
            "SHA256SUMS.txt",
        ):
            self.assertIn(marker, windows)
        self.assertIn('$env:CGO_ENABLED = "0"', windows)
        self.assertIn(
            '$EnvironmentNames = @("CGO_ENABLED", "GOAMD64", "GO386", "GOARM64")',
            windows,
        )
        self.assertIn('Remove-Item -Path "Env:$Name"', windows)
        for platform, suffix in (
            ("windows/amd64", "x64"),
            ("windows/386", "x86"),
            ("windows/arm64", "arm64"),
        ):
            self.assertIn(platform, windows)
            self.assertIn(f'Windows-{suffix}.exe"', windows)

''',
)
replace_regex(
    release_helpers,
    r"^    def test_release_gate_uses_current_gitleaks_cli_and_embedded_data_audit\(self\):.*?(?=^    def test_release_requires_successful_ci_codeql_and_unchanged_artifact)",
    r'''    def test_release_gate_uses_current_gitleaks_cli_and_embedded_data_audit(self):
        paths = (
            ROOT / ".github" / "workflows" / "ci.yml",
            ROOT / "scripts" / "windows" / "IrisTools.ps1",
        )
        combined = "\n".join(path.read_text(encoding="utf-8") for path in paths)
        self.assertNotIn("--source", combined)
        self.assertIn("data_presentation_audit.py", combined)
        self.assertIn("function Test-GitleaksDetection", combined)
        self.assertIn("Gitleaks functional detection self-test failed.", combined)
        self.assertIn("Invoke-GitleaksHistoryScan", combined)
        self.assertIn("Test-GitleaksHistoryProof", combined)
        self.assertIn("ConvertFrom-AnsiToolOutput", combined)
        self.assertIn("commits scanned", combined)
        self.assertIn("--exit-code", combined)
        self.assertNotIn("python3 -B tools/raw_projection_audit.py\n", combined)
        self.assertNotIn("python3 -B tools/drop_table_audit.py\n", combined)

''',
)
replace_exact(
    release_helpers,
    '''        for check in (\n            "Linux quality and security",\n            "Go race detector",\n            "Native Windows Wails release matrix",\n            "Analyze (go)",\n            "Analyze (python)",\n        ):''',
    '''        for check in (\n            "Windows quality and security",\n            "Windows race detector",\n            "Native Windows Wails release matrix",\n            "Analyze (go)",\n            "Analyze (python)",\n        ):''',
)
replace_exact(
    release_helpers,
    '''        self.assertIn("go-version-file: .go-version", workflow)\n        self.assertIn("go-version-file: .go-version", codeql)\n        self.assertIn('iris_run_govulncheck "$(command -v govulncheck)" 15m', workflow)\n        release_tools = (ROOT / "scripts" / "release-tools.sh").read_text(\n            encoding="utf-8"\n        )\n        self.assertIn("export GOTOOLCHAIN=local", release_tools)''',
    '''        self.assertIn("go-version-file: .go-version", workflow)\n        self.assertIn("go-version-file: .go-version", codeql)\n        self.assertIn("govulncheck@v1.6.0", workflow)\n        self.assertNotIn("ubuntu-", workflow)\n        self.assertNotIn("ubuntu-", codeql)''',
)
replace_regex(
    release_helpers,
    r"^    def test_shell_release_tools_do_not_trust_wails_path_or_version_text\(self\):.*?(?=^    def test_release_assets_are_exact_and_checksum_verified)",
    r'''    def test_release_tooling_is_windows_only_and_uses_verified_resolvers(self):
        for name in ("release-tools.sh", "release-gate.sh", "build-release.sh"):
            self.assertFalse((ROOT / "scripts" / name).exists(), name)
        windows = (ROOT / "scripts" / "windows" / "IrisTools.ps1").read_text(
            encoding="utf-8"
        )
        self.assertIn("go version -m", windows)
        self.assertIn("github.com/wailsapp/wails/v2/cmd/wails", windows)
        self.assertIn("Get-PinnedWailsExecutable", windows)
        self.assertIn("Get-PinnedStaticcheckExecutable", windows)
        self.assertIn("Get-PinnedGovulncheckExecutable", windows)
        self.assertIn("Invoke-Govulncheck", windows)
        self.assertIn("Test-GitleaksDetection", windows)
        self.assertIn("Invoke-GitleaksHistoryScan", windows)
        self.assertNotIn('Invoke-Checked "wails" @(', windows)

''',
)
replace_regex(
    release_helpers,
    r"^    def test_release_shell_scripts_are_real_executables\(self\):.*?(?=^    def test_frontend_smoke_redacts_missing_browser_details)",
    r'''    def test_release_tooling_has_no_posix_release_scripts(self):
        self.assertFalse(any((ROOT / "scripts").glob("*.sh")))
        self.assertTrue((ROOT / "IrisTools.ps1").is_file())
        self.assertTrue((ROOT / "scripts" / "windows" / "IrisTools.ps1").is_file())
        self.assertTrue((ROOT / "scripts" / "windows" / "00_RELEASE_WINDOWS.bat").is_file())

''',
)
replace_exact(
    release_helpers,
    "                # runnable by a normal non-elevated user; Linux CI still exercises\n                # the symlink-specific branch when Windows cannot create one.\n",
    "                # runnable by a normal non-elevated user. Manifest rejection is\n                # still tested even when this optional Windows privilege is absent.\n",
)

# Add direct regression coverage for the Windows EOL and Python-cache incidents.
write_lf(
    "tests/test_line_endings_contract.py",
    r'''import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class LineEndingsContractTests(unittest.TestCase):
    def test_language_sources_are_checked_out_with_lf_on_windows(self):
        attributes = (ROOT / ".gitattributes").read_text(encoding="utf-8")
        lines = attributes.splitlines()
        self.assertIn("*.go text eol=lf", lines)
        self.assertIn("*.py text eol=lf", lines)

    def test_windows_launchers_use_crlf_checkout(self):
        attributes = (ROOT / ".gitattributes").read_text(encoding="utf-8")
        lines = attributes.splitlines()
        self.assertIn("*.ps1 text eol=crlf", lines)
        self.assertIn("*.bat text eol=crlf", lines)


if __name__ == "__main__":
    unittest.main()
''',
)

# All release-facing docs/tests must stop naming the deleted shell release files.
for relative in (
    "README.md",
    "docs/BUILD.md",
    "docs/RELEASE.md",
    "CONTRIBUTING.md",
    "tests/test_quality_contract.py",
    "tests/test_release_helpers.py",
    "tools/validate_workflows.py",
):
    text = read(relative)
    for forbidden in ("scripts/release-gate.sh", "scripts/build-release.sh", "scripts/release-tools.sh"):
        if forbidden in text:
            raise RuntimeError(f"{relative}: legacy release reference remains: {forbidden}")

print("Windows-only migration source edits: PASS")
